version: '3'

services:

  #middleware_db
  db:
    container_name: middleware_db
    image: postgres:15
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # rtsptoweb:
  roverr_rtsp_stream:
    restart: always
    image: ghcr.io/deepch/rtsptoweb:latest
    container_name: roverr_rtsp_stream
    volumes:
      - ./config.json:/config/config.json
    ports:
      - "8080:8080"
    logging:
        options:
            max-size: "10m"
            max-file: "3"

  # teleicu_middleware
  teleicu_middleware:
    restart: always
    image: ghcr.io/ohcnetwork/teleicu_middleware:production-latest
    container_name: teleicu_middleware
    env_file:
      - ./.env
    ports:
      - "8090:8090"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # proxies requests to internal services
  reverse-proxy:
    restart: always
    image: ghcr.io/ohcnetwork/teleicu_nginx/teleicu_nginx:latest
    container_name: reverse-proxy
    depends_on:
      - teleicu_middleware
    ports:
      - "8001:8001"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  #watchtower
  watchtower:
    restart: always
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_SCHEDULE=0 * * * * *
    ports:
      - "8070:8080"
    logging:
      options:
        max-size: "10m"
        max-file: "3"

#  # mock_cns_req
#  mock_cns_req:
#    restart: always
#    image: ghcr.io/ohcnetwork/mock-cns-req:latest
#    container_name: mock_cns_req
#    ports:
#    - "8002:8002"
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "3"

volumes:
  postgres-data:
